"""first commit

Revision ID: febac860b3ff
Revises: 
Create Date: 2020-03-11 17:37:51.571742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febac860b3ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=256), nullable=False),
    sa.Column('model_no', sa.String(length=256), nullable=False),
    sa.Column('mrp', sa.Integer(), nullable=False),
    sa.Column('offer_pr', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    # ### end Alembic commands ###
